MODEL:
  META_ARCHITECTURE: "SingleStageDetector"
  WEIGHT: "models/R-50-NAS.pth"
  RPN_ONLY: True
  DENSEBOX_ON: True
  BACKBONE:
    CONV_BODY: "R-50-NAS"
    OUT_CHANNELS: 256
    ENCODER_OUT_CHANNELS: (256, 512, 1024, 2048)
  RPN:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 81
  RETINANET:
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: -1
    NUM_CLASSES: 81
    NMS_TH: 0.6
    USE_C5: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  # TEST: ("coco_2017_test_dev",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2
SEARCH:
  DECODER:
    VERSION: 2
    CONFIG: [[[3, 3, 4, 4, 1]], [[3, 3, 4, 4, 1]], [[4, 3, 4, 3, 1]], [[1, 3, 4, 3, 1]], [[5, 3, 4, 4, 1]], [[4, 7, 4, 4, 1]], [[7, 2, 4, 4, 1]]]
    AGG_SIZE: 256
    NUM_CELLS: 7
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000,80000,)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  NUM_GPUS: 4
TEST:
  IMS_PER_BATCH: 8
OUTPUT_DIR: 'output/coco/r50-NAS'
